defmodule DemoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :demo

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_demo_key",
    signing_salt: "uO7xOb/m",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :demo,
    gzip: not code_reloading?,
    only: DemoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # A one-pixel PNG served with a permissive CORS header, so the browser test
  # can paste an image from "another host" and watch it be captured. Reached
  # through 127.0.0.1 while the page is on localhost: different origins, same
  # server.
  plug :remote_image

  defp remote_image(%Plug.Conn{path_info: ["remote-image.png"]} = conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("access-control-allow-origin", "*")
    |> Plug.Conn.put_resp_content_type("image/png")
    |> Plug.Conn.send_resp(200, Demo.Uploads.pixel())
    |> Plug.Conn.halt()
  end

  defp remote_image(conn, _opts), do: conn

  # Serves attachment bytes behind a signature, before the router sees them.
  plug Coelho.Plug.Attachments,
    at: "/attachments",
    storage: {Demo.Uploads, :storage, []},
    secret: {Demo.Uploads, :secret, []},
    metadata: {Demo.Uploads, :metadata, []}

  plug DemoWeb.Router
end
